services:
  dutt-qr-menu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dutt-qr-menu
    restart: unless-stopped
    environment:
      - PORT=3000
      - ADMIN_USERNAMES=admin,dutt,duttmeyhane
      - ADMIN_PASSWORDS=dutt123,DuttMersin.2026!
      - DB_PATH=/app/storage/db.json
      - ANALYTICS_PATH=/app/storage/analytics.json
    volumes:
      - ./storage:/app/storage
      - ./src/data:/app/src/data
      - ./public/uploads:/app/public/uploads
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dutt-http.entrypoints=http"
      - "traefik.http.routers.dutt-http.middlewares=redirect-to-https"
      - "traefik.http.routers.dutt-http.rule=Host(`dutt.mokaworks.tr`)"
      - "traefik.http.routers.dutt-https.entrypoints=https"
      - "traefik.http.routers.dutt-https.rule=Host(`dutt.mokaworks.tr`)"
      - "traefik.http.routers.dutt-https.tls=true"
      - "traefik.http.routers.dutt-https.tls.certresolver=letsencrypt"
      - "traefik.http.services.dutt.loadbalancer.server.port=3000"

networks:
  coolify:
    external: true
